### ISSUE TITLE
ranges not correct for restaurant when running initialiser

### ISSUE THREAD

**Issue by Bourkupine** [Bourkupine/CS4013-group-project#13]
<img width="305" alt="Screenshot 2022-11-18 at 14 21 33" src="https://user-images.githubusercontent.com/30806087/202726357-1c6fb2e6-defc-4e7a-b0cd-9f29cf16ca7b.png">

**Comment by Bourkupine** [comment]
could maybe say "enter id less that 1" rather than between 0 and 1 or have an if statement that checks for this

**Comment by RLynch59** [comment]
Fixed
